### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by straithe**

### CODE REVIEW

**Comment by FFY00** [comment]
FWIW, I would prefer that you follow the existing commit naming scheme in this project if you can remember :blush:

I realize I may be being a bit too picky, but if this gives you any trouble, feel free to wait for me to merge and I'll tidy things up then. Thanks! And sorry :sweat_smile:

**Comment by straithe** [comment]
Can you give more detail?

**Comment by FFY00** [comment]
Yup, sorry, I have been meaning to write a contribution guide. I'd like for commits to prefixed by the component they are changing, in this case I'd probably use `coc`, so the commit could be something like `coc: add code of conduct`. This helps navigate the git history, which is also documentation!, but maybe that is just my dyslexic brain trying to optimize.

If you have any questions, you can always ping me directly. If I take too long to respond, don't feel bad and just move forward with whatever you think is the best option. This is only valid as long as it is making things better, I don't want it to block progress or negatively impact the project in any way.

**Comment by straithe** [comment]
Thank you! I appreciate the extra information!

**Pull request merged**
